DROP ALL OBJECTS;
CREATE TABLE MY_TABLE(ID INT PRIMARY KEY, NAME VARCHAR);
INSERT INTO MY_TABLE VALUES(1, 'Hello World 1');
INSERT INTO MY_TABLE VALUES(2, 'Hello World 2');
INSERT INTO MY_TABLE VALUES(3, 'Hello World 3');